name: generate-lambda-layer
on: [workflow_dispatch]
jobs:
    build-layer-zip:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup Python 3.13
              uses: actions/setup-python@v6
              with:
                python-version: 3.13
            - name: Install dependencies
              run: |
                mkdir python
                pip install --platform manylinux2014_aarch64 --target=python --implementation cp --python-version 3.13 --only-binary=:all: --upgrade -r server/requirements.txt
                zip --quiet -r python.zip python
            - name: Create artifact
              uses: actions/upload-artifact@v3
              with:
                name: python
                path: python.zip
            